config/routes.rb
Rails.application.routes.draw do

  resources :quotes

  root to: 'quotes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord

  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  expose(:quotes) { Quote.all.page params[:page]}
  expose(:quote)

  def show
    redirect_to(action: :index)
  end

  def create
    if quote.save
      redirect_to(action: :index)
    else
      render :new
    end
  end

  def update
    if quote.update(quote_params)
      redirect_to(action: :index)
    else
      render :edit
    end
  end

  def destroy
    quote&.destroy
    quote&.destroyed? && redirect_to(action: :index)
  end

  private

    def quote_params
      params.require(:quote).permit(:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_breadcrumbs.slim
ol.breadcrumb
  - breadcrumbs(display_single_fragment: true).tap do |links|
    - if links.any?
      - links.each do |link|
        li.breadcrumb-item
          = link_to link.text, link.url, class: (link.current? ? 'breadcrumb-item active' : 'breadcrumb-item')

app/views/application/_cover.slim
.cover.text-center
  .container
    .row
      .col
        .cover__title Quotes of the world
  .cover__background

app/views/application/_navbar.slim
nav.navbar.sticky-top.navbar-dark.bg-dark
  .navbar-brand
    = render 'breadcrumbs'
  form.form-inline
    = link_to 'New quote', new_quote_path , class: 'btn btn-secondary'

app/views/layouts/application.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type"
    title Quotation
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = render 'navbar'
    = render 'cover'

    .container-fluid
      = yield

app/views/quotes/_form.slim
= simple_form_for quote do |f|
  .card.text-white.bg-dark
    .card-header Quote body
    .card-body
      = f.input :body, as: :text, label: false, input_html: { rows: 5 }
      = link_to 'Go back', quotes_path, class: 'btn btn-secondary'
      = f.button :submit, 'Save', class: 'btn btn-secondary float-right'

app/views/quotes/_quote.slim
.col-sm-6
  .card.text-white.bg-dark
    .card-header
      | Quote ##{quote.id}
    .card-body
      blockquote.blockquote
        p = quote.body
        footer.blockquote-footer
          | Someone famous

app/views/quotes/edit.slim
- breadcrumb :quotes_edit
= render 'form'

app/views/quotes/index.slim
- breadcrumb :quotes_index

.row
  = render quotes
.pagination.justify-content-center
  = paginate quotes

app/views/quotes/new.slim
- breadcrumb :quotes_new
= render 'form'